version: '3'

services:

  inference:
      image: danielj4mv/t4:latest
      
      container_name: inference
      
      deploy:
        mode: replicated
        replicas: 1

        resources:
          limits:
            cpus: '2'
            memory: 500M
          reservations:
            cpus: '0.25'
            memory: 200M
            
      ports:
        - '8083:8083'
        
      restart: always
      
      networks:
      - network1
      
networks:
  network1:
    name: p2_default
    external: true
